<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'num_partner' => 1,
                'nickname' => 'RyU',
                'name' => 'RyuAdmin',
                'password' => bcrypt('RyuAdmin'),
                'type' => 'admin',
                'registration_date' => now(),
                'email' => 'ryuadmin@zas.es',
                'telephone' => '1234567890',
                'age' => 44,
            ],        
            [
                'num_partner' => 2,
                'nickname' => 'RyuJunta',
                'name' => 'RyuJunta',
                'password' => bcrypt('RyuJunta'),
                'type' => 'junta',
                'registration_date' => now(),
                'email' => 'ryujunta@zas.es',
                'telephone' => '1122334455',
                'age' => 44,
            ],
            [
                'num_partner' => 3,
                'nickname' => 'RyuPartner',
                'name' => 'RyuPartner',
                'password' => bcrypt('RyuPartner'),
                'type' => 'partner',
                'registration_date' => now(),
                'email' => 'ryupartner@zas.es',
                'telephone' => '5555555555',
                'age' => 44,
            ],
            [
                'num_partner' => 4,
                'nickname' => 'RyuGuest',
                'name' => 'RyuGuest',
                'password' => bcrypt('RyuGuest'),
                'type' => 'guest',
                'registration_date' => now(),
                'email' => 'ryuguest@zas.es',
                'telephone' => '9999999999',
                'age' => 44,
            ],        
            [
                'num_partner' => 5,
                'nickname' => 'RubenAdmin',
                'name' => 'Ruben',
                'password' => bcrypt('RubenAdmin'),
                'type' => 'admin',
                'registration_date' => now(),
                'email' => 'rubenadmin@zas.es',
                'telephone' => '0987654321',
                'age' => 35,
            ],
            [
                'num_partner' => 6,
                'nickname' => 'RubenJunta',
                'name' => 'RubenJunta',
                'password' => bcrypt('RubenJunta'),
                'type' => 'junta',
                'registration_date' => now(),
                'email' => 'rubenjunta@zas.es',
                'telephone' => '1111111111',
                'age' => 35,
            ],
            [
                'num_partner' => 7,
                'nickname' => 'RubenPartner',
                'name' => 'RubenPartner',
                'password' => bcrypt('RubenPartner'),
                'type' => 'partner',
                'registration_date' => now(),
                'email' => 'rubenpartner@zas.es',
                'telephone' => '2222222222',
                'age' => 35,
            ],
            [
                'num_partner' => 8,
                'nickname' => 'RubenGuest',
                'name' => 'RubenGuest',
                'password' => bcrypt('RubenGuest'),
                'type' => 'guest',
                'registration_date' => now(),
                'email' => 'rubenguest@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 9,
                'nickname' => 'Edu',
                'name' => 'Edu',
                'password' => bcrypt('EduGil'),
                'type' => 'junta',
                'registration_date' => now(),
                'email' => 'edu@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 10,
                'nickname' => 'Dama',
                'name' => 'Dama',
                'password' => bcrypt('DamaSirys'),
                'type' => 'junta',
                'registration_date' => now(),
                'email' => 'dama@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 11,
                'nickname' => 'Leo',
                'name' => 'Leo',
                'password' => bcrypt('Marina'),
                'type' => 'partner',
                'registration_date' => now(),
                'email' => 'leo@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 12,
                'nickname' => 'Iris',
                'name' => 'Iris',
                'password' => bcrypt('IrisCarla'),
                'type' => 'junta',
                'registration_date' => now(),
                'email' => 'iris@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 13,
                'nickname' => 'Ivan',
                'name' => 'Ivan',
                'password' => bcrypt('Ivan123'),
                'type' => 'partner',
                'registration_date' => now(),
                'email' => 'ivan@zas.es',
                'telephone' => null,
                'age' => 35,
            ],
            [
                'num_partner' => 14,
                'nickname' => 'Clara',
                'name' => 'Clara',
                'password' => bcrypt('Clara69'),
                'type' => 'guest',
                'registration_date' => now(),
                'email' => 'clara@nozas.es',
                'telephone' => null,
                'age' => 35,
            ],
        ]);
    }
}
